@startuml
abstract class Zone {
	- String code
	- String nom
	- StatutZone status
	- double latitudeMin
	- double latitudeMax
	- double longitudeMin
	- double longitudeMax
	- List<Capteur> capteurs
	- List<Releve> releves
	- List<Alerte> alertes
	+ contientPosition(PositionGPS position)
	+ ajouterCapteur(Capteur capteur)
}

class ZoneCulture {
	- List<Culture> cultures
	- double rendement
}

class ZoneElevage {
	- List<Animal> animaux
	- TypeElevage typeElevage
	- ProgrammeAlimentation programmeAlimentation
	- double rendementLaitier
	- double productionOeufs
	+ ajouterAnimal(Animal animal)
}

class ZoneAquacole {
	- List<Bassin> bassins
	- ProgrammeAlimentation programmeAlimentation
	- double poidsRecolte
}

class SmartFarmingSystem {
	- List<Zone> zones
	- List<Releve> releves
	- List<Alerte> alertes
	- List<RapportProduction> rapports
	+ ajouterZone(Zone zone)
	+ recevoirReleve(Releve releve)
	+ simulerCycleReleves(Random random)
	+ enregistrerReleveNumerique(CapteurNumerique capteur, double valeur)
	+ enregistrerReleveGPS(CapteurGPS capteur, double latitude, double longitude)
}

class ResultatSimulation {
	- LocalDateTime dateHeure
	- int nombreRelevesGeneres
	- int nombreAlertesGenerees
}

abstract class Animal {
	- int id
	- EspeceAnimale espece
	- int age
	- double poids
	- EtatSante etatSante
	- List<EvenementSanitaire> historiqueSante
	+ getTypeElevage()
}

class Ruminant
class Volaille

class EvenementSanitaire {
	- String id
	- LocalDateTime dateHeure
	- Animal animal
	- String description
	- EtatSante etatSante
	- Double ancienPoids
	- Double nouveauPoids
}

class ProgrammeAlimentation {
	- String typeAliment
	- double quantiteParRepas
}

class Culture
class Bassin

abstract class Capteur {
	- String id
	- String nom
	- StatutCapteur statut
	- Zone zone
	+ reparer()
}

abstract class CapteurNumerique {
	- UniteMesure unite
	- double seuilMin
	- double seuilMax
	- List<ReleveNumerique> historique
	+ envoyerReleve(Random random)
	+ creerReleve(double valeur)
}

abstract class CapteurEnvironnemental
abstract class CapteurSol
abstract class CapteurBiometrique {
	- Animal animal
}
abstract class CapteurEau

class CapteurTemperatureAir
class CapteurHumiditeAir
class CapteurPluviometrie
class CapteurPHSol
class CapteurHumiditeSol
class CapteurAzote
class CapteurTemperatureCorporelle
class CapteurActivite
class CapteurTemperatureEau
class CapteurOxygeneDissous
class CapteurPHEau
class CapteurGPS {
	- double latitude
	- double longitude
	- List<ReleveGPS> historiqueGPS
	+ envoyerReleve(Random random)
}

abstract class Releve {
	- String id
	- LocalDateTime dateHeure
	- Capteur capteur
	- NiveauGravite niveauGravite
}

class ReleveNumerique {
	- Double valeur
	- UniteMesure unite
}

class ReleveGPS {
	- PositionGPS position
}

class PositionGPS {
	- double latitude
	- double longitude
}

class Alerte {
	- String id
	- LocalDateTime dateHeure
	- String message
	- StatutAlerte statut
	- Zone zone
	- Releve releveDeclencheur
}

class RapportProduction

enum TypeElevage
enum StatutZone
enum StatutCapteur
enum StatutAlerte
enum NiveauGravite
enum UniteMesure
enum EspeceAnimale
enum EspeceAquacole
enum EtatSante

Zone <|-- ZoneCulture
Zone <|-- ZoneElevage
Zone <|-- ZoneAquacole
SmartFarmingSystem "1" o-- "*" Zone
SmartFarmingSystem "1" o-- "*" Releve
SmartFarmingSystem "1" o-- "*" Alerte
SmartFarmingSystem "1" o-- "*" RapportProduction
SmartFarmingSystem ..> ResultatSimulation

ZoneCulture "1" o-- "*" Culture
ZoneElevage "1" o-- "*" Animal
ZoneElevage "1" --> "1" TypeElevage
ZoneElevage "1" --> "1" ProgrammeAlimentation
ZoneAquacole "1" o-- "*" Bassin
ZoneAquacole "1" --> "1" ProgrammeAlimentation
Zone "1" o-- "*" Capteur
Zone "1" o-- "*" Releve
Zone "1" o-- "*" Alerte

Animal <|-- Ruminant
Animal <|-- Volaille
Animal "1" o-- "*" EvenementSanitaire
Animal "*" --> "1" EspeceAnimale
Animal "*" --> "1" EtatSante

Capteur <|-- CapteurNumerique
Capteur <|-- CapteurGPS
CapteurNumerique <|-- CapteurEnvironnemental
CapteurNumerique <|-- CapteurSol
CapteurNumerique <|-- CapteurBiometrique
CapteurNumerique <|-- CapteurEau
CapteurEnvironnemental <|-- CapteurTemperatureAir
CapteurEnvironnemental <|-- CapteurHumiditeAir
CapteurEnvironnemental <|-- CapteurPluviometrie
CapteurSol <|-- CapteurPHSol
CapteurSol <|-- CapteurHumiditeSol
CapteurSol <|-- CapteurAzote
CapteurBiometrique <|-- CapteurTemperatureCorporelle
CapteurBiometrique <|-- CapteurActivite
CapteurEau <|-- CapteurTemperatureEau
CapteurEau <|-- CapteurOxygeneDissous
CapteurEau <|-- CapteurPHEau

Releve <|-- ReleveNumerique
Releve <|-- ReleveGPS
ReleveGPS "1" --> "1" PositionGPS
Releve "*" --> "1" NiveauGravite
Alerte "*" --> "1" Releve : declenchee par
Alerte "*" --> "1" StatutAlerte
Capteur "*" --> "1" StatutCapteur
CapteurNumerique "*" --> "1" UniteMesure
@enduml
